menu:
# - {name: 'people', url: '/people'}
- {name: 'Publications', url: '/publications'}
- {name: 'CV', url: '/cv'}

contacts:
- {name: 'Alif Al Hasan', title: 'Student', department: 'Computer Science and Engineering', institution: 'Jahangirnagar University', institution_address: 'Savar, Dhaka, Bangladesh', email: 'alif [dot] stu2017 [at] juniv [dot] edu', office: 'Lab-201, Department of Computer Science and Engineering', image: 'assets/img/alifalhasan.jpg'}
